{{ set name = "genutil" }}
{{ set version = "8.1" }}
package:
    name: genutil
    version: {{ version }}.np{{ numpy }}

source:
    url: https://github.com/cdat/{{ name }}/archive/v8.0.tar.gz
    sha256: 1e0b1a74422030e321fad62307a5246fe728654d40462786b0a030ef5c1f37f6

build:
  number: 0
 
requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python {{ python }}
    - setuptools
    - numpy >1.11.*
    - udunits2
  run:
    - python {{ python }}
    - cdms2
    - udunits2
    - {{ pin_compatible('numpy') }}

about:
    home:  http://gitub.com/CDAT/genutil



