{% set name = "genutil" %}
{% set version = "3.00" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/genutil/archive/master.tar.gz
    sha256: b3b4ad208ae996222e79eaf02d6e6225eb35f6ec6b7183389114f6912cfab19f

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy  1.11.*
    - udunits2
    - toolchain  # [osx]
  run:
    - python
    - cdms2
    - numpy >=1.11
    - udunits2

test:
    commands:
        - export UVCDAT_ANONYMOUS_LOG=false && python -c "import genutil"

about:
    home:  http://gitub.com/UV-CDAT/genutil
    license: 'CCLRC'
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
