{% set name = "genutil" %}
{% set version = "8.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/CDAT/genutil/archive/v{{ version }}.tar.gz
    sha256: 81dcab37026b6b718a5c339439dcd3d286c84820b8c286749b9c6951f482a389


build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy  1.11.*
    - udunits2
    - toolchain  # [osx]
    - cdat_info
  run:
    - python
    - cdms2
    - numpy >=1.11
    - udunits2

test:
    commands:
        - export UVCDAT_ANONYMOUS_LOG=false && python -c "import genutil"

about:
    home:  http://gitub.com/CDAT/genutil
    license: 'CCLRC'
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
