{% set name = "genutil" %}
{% set version = "3.00" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/genutil/archive/master.tar.gz
    sha256: bec6bf52ab161cc8775368e7ffb14f9d6adbae3b8073a44e2592de92b303c159
    

build:
  number: 1
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - setuptools
    - numpy 
    - udunits2
    - toolchain  # [osx]
  run:
    - python
    - cdms2
    - numpy 
    - udunits2

test:
    command:
        - export UVCDAT_ANONYMOUS_LOG=false && python run_tests.py -v2

about:
    home:  http://gitub.com/UV-CDAT/genutil
    license: 'CCLRC'
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
